config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations"}

  namespace :signup do
    resources :members, only: [:new, :create]
    scope :documents do
      get :agreement, to: "documents#agreement"
      get :rules, to: "documents#rules"

      resource :acceptance, only: [:create, :destroy]
    end
    resources :payments, only: [:new, :create] do
      get :callback, on: :collection
      post :skip, on: :collection
    end
    resources :redemptions, only: [:new, :create]

    get "confirmation", to: "confirmations#show"
    get "/", to: "home#index"
  end

  namespace :account do
    resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :borrow_policy_approvals, only: [:create]
    resources :holds, only: [:index, :create, :destroy] do
      get :history, to: "holds#history", on: :collection
    end
    resources :loans, only: :index do
      get :history, to: "loans#history", on: :collection
      post :renew_all, to: "loans#renew_all", on: :collection
    end
    resource :member, only: [:show, :edit, :update]
    get :agreement, to: "members#agreement"
    get :code_of_conduct, to: "members#code_of_conduct"
    get :borrow_policy, to: "members#borrow_policy"
    resource :password, only: [:edit, :update]
    resources :renewals, only: :create
    resources :renewal_requests, only: :create
    resources :for_later_list_items, path: :for_later, only: [:index, :create, :destroy]
    get "/", to: "home#index", as: "home"

    if FeatureFlags.reservable_items_enabled?
      resources :reservation_holds, only: [:create, :update, :destroy]
      resource :current_reservation, only: [:create, :destroy]
      resources :reservations do
        get :past, to: "reservations#past", on: :collection
        scope module: "reservations" do
          resources :reservation_holds
          resource :submission
        end
      end
      resources :item_pools
    end
  end

  namespace :renewal do
    resource :member, only: [:edit, :update]
    scope :documents do
      get :agreement, to: "documents#agreement"
      get :rules, to: "documents#rules"

      resource :acceptance, only: [:create, :destroy]
    end
    resources :payments, only: [:new, :create] do
      get :callback, on: :collection
      post :skip, on: :collection
    end
    resources :redemptions, only: [:new, :create]

    get "confirmation", to: "confirmations#show"
    get "/", to: "home#index"
  end

  namespace :volunteer do
    resources :shifts, only: [:index, :create, :destroy]
    resources :attendees, only: [:create, :destroy]
    get "event", to: "shifts#event"
    resource :session, only: [:destroy]
  end
  get "/auth/google_oauth2/callback", to: "volunteer/sessions#create"
  get "/auth/failure", to: "volunteer/sessions#failure"

  namespace :admin do
    resources :documents, only: [:show, :edit, :update, :index]
    resources :borrow_policies, only: [:index, :edit, :update, :show] do
      resources :borrow_policy_approvals, only: [:index, :edit, :update, :create], path: :approvals
    end
    resources :categories, except: :show
    resources :gift_memberships
    resources :questions, except: [:destroy] do
      patch :archive, on: :member
      patch :unarchive, on: :member
    end
    resources :appointments, only: [:index, :show, :edit, :update, :destroy] do
      resources :holds, only: [:create, :destroy], controller: :appointment_holds
      resources :loans, only: [:create, :destroy], controller: :appointment_loans
      resources :checkouts, only: [:create], controller: :appointment_checkouts
      resources :checkins, only: [:create], controller: :appointment_checkins
      resource :completion, only: [:create, :destroy], controller: :appointment_completions
      resource :pull, only: [:create, :destroy], controller: :appointment_pulls
      resource :detail_completion, only: [:create, :destroy], controller: :appointment_detail_completions
      resource :detail_pull, only: [:create, :destroy], controller: :appointment_detail_pulls
    end
    resources :manage_features, only: [:index, :update]
    resources :items do
      scope module: "items" do
        resources :attachments
        resource :loan_history, only: :show
        resource :history, only: :show
        resources :holds, only: :index do
          patch :remove, action: "remove"
          scope module: "holds" do
            resource :position, only: :update
          end
        end
        resources :notes
        if ENV["FEATURE_MAINTENANCE_WORKFLOW"] == "on"
          resources :tickets do
            scope module: "tickets" do
              resources :ticket_updates, only: [:new, :create, :edit, :update, :destroy]
            end
          end
        end
      end

      get :number
      resource :image, only: [:edit, :update]
      # resource :manual_import, only: [:edit, :update]
    end
    resources :loan_summaries, only: :index
    resources :loans, only: [:index, :create, :update, :destroy]
    resources :renewals, only: [:create, :destroy]
    resources :bulk_renewals, only: [:update]

    resources :members do
      scope module: "members" do
        resources :holds, only: [:create, :index, :destroy] do
          post :lend, on: :member
          get :history, on: :collection
        end
        resource :hold_loan, only: :create
        resource :lookup, only: :show
        resources :memberships, only: [:index, :new, :create, :update]
        resources :payments, only: [:new, :create]
        resource :verification, only: [:edit, :update]
        resources :appointments, only: [:index, :create]
        resources :notifications, only: :index
        resources :loan_summaries, only: :index
        resources :notes
        resource :password, only: [:edit, :update]
      end

      member do
        post :resend_verification_email
      end
    end

    namespace :reports do
      resources :memberships, only: :index
      resources :items_in_maintenance, only: :index
      resources :missing_items, only: :index
      resources :monthly_activities, only: :index
      resources :member_requests, only: :index
      resources :notifications, only: :index
      resources :potential_volunteers, only: :index
      resources :shifts, only: :index
      resources :items_without_image, only: :index
      resources :items_with_holds, only: :index
      resources :zipcodes, only: :index
      get "money", to: "money#index"
      get "members-with-overdue-loans", to: "members_with_overdue_loans#index"
    end

    namespace :settings do
      get "closing", to: "closing#index"
      post "closing/extend_holds", to: "closing#extend_holds"
      resource :email_settings do
        get :preview, on: :member
      end
      resources :library_updates
      resources :exports, only: [:index] do
        post :items, on: :collection
        post :members, on: :collection
      end
    end

    resources :holds, only: [:index]
    resources :users
    resources :renewal_requests, only: [:index, :update]

    get "search", to: "searches#show"

    get "/ui/names", to: "ui#names"
    get "/ui/brands", to: "ui#brands"
    get "/ui/sizes", to: "ui#sizes"
    get "/ui/strengths", to: "ui#strengths"
    get "/ui/available_items", to: "ui#available_items"
    get "/ui/members", to: "ui#members"

    if FeatureFlags.reservable_items_enabled?
      resources :reservation_policies
      resources :item_pools do
        scope module: "item_pools" do
          resource :availability, only: :show
          resources :reservable_items
        end
      end
      resources :reservations do
        scope module: "reservations" do
          resources :items, as: "loans", controller: "reservation_loans", only: [:index, :create, :destroy]
          resources :check_ins, only: [:create, :destroy]
          resources :reservation_holds
          resources :pending_reservation_items, only: [:update, :destroy]
          resource :status, only: :update
          resource :review, only: [:edit, :update, :show]
          resource :item_pool_search, only: :show
          resource :questions, only: :show
        end
      end
    end

    get "/", to: "dashboard#index", as: "dashboard"
  end

  if Rails.env.development?
    post "/dev/time", to: "dev#set_time"
    delete "/dev/time", to: "dev#clear_time"
  end

  get "/dev/styles", to: "dev#styles"

  namespace :super_admin do
    resources :libraries
  end

  resources :items, only: [:index, :show]
  if FeatureFlags.reservable_items_enabled?
    resources :item_pools, only: [:index, :show], path: "camping_items"
    resources :reservation_holds, only: :create
  end
  resources :documents, only: :show

  post "/twilio/callback", to: "twilio#callback"

  # Mount dashboards for admins
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    mount Blazer::Engine => "blazer"
  end

  root to: "home#index"

  if Rails.env.test?
    get "/test/google_auth", to: "test#google_auth"
  end

  %w[404 406 422 500 503].each do |code|
    match code, to: "errors#show", via: :all, code: code, as: "error_#{code}"
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUS_NAMES = {
    "assess" => "Assess",
    "repairing" => "Repair in Progress",
    "parts" => "Parts on Order",
    "resolved" => "Resolved",
    "retired" => "Retired"
  }

  STATUS_DESCRIPTIONS = {
    "assess" => "newly created; needs examination by maintenance team",
    "parts" => nil,
    "repairing" => nil,
    "resolved" => "the problem has been fixed",
    "retired" => "removed from inventory"
  }

  enum :status, {
    assess: "assess",
    parts: "parts",
    repairing: "repairing",
    resolved: "resolved",
    retired: "retired"
  }

  belongs_to :item
  belongs_to :creator, class_name: "User"
  has_many :ticket_updates, dependent: :destroy
  has_one :latest_ticket_update, -> { newest_first }, class_name: "TicketUpdate"

  has_rich_text :body

  acts_as_taggable_on :tags

  validates :title, presence: true
  validates :status, inclusion: {in: Ticket.statuses.keys}

  audited except: :tag_list
  acts_as_tenant :library

  scope :active, -> { where(status: Ticket.statuses.values_at(:assess, :parts, :repairing)) }
  scope :newest_first, -> { order(created_at: :desc) }
  # used for filtering--if no tags are selected, don't filter by tags
  scope :has_tags, ->(tags) do
    if tags.present?
      tagged_with(tags)
    else
      all
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at updated_at title status]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[item]
  end
end

app/models/ticket_update.rb
class TicketUpdate < ApplicationRecord
  belongs_to :ticket, touch: true
  belongs_to :creator, class_name: "User"
  belongs_to :audit, class_name: "Audited::Audit", optional: true

  has_rich_text :body
  validates :body, presence: true
  validates :time_spent, numericality: {allow_blank: true}

  acts_as_tenant :library

  scope :newest_first, -> { order(created_at: :desc) }
end

app/controllers/admin/items/tickets/ticket_updates_controller.rb
module Admin
  module Items
    module Tickets
      class TicketUpdatesController < BaseController
        before_action :set_ticket
        before_action :set_ticket_update, only: [:edit, :update, :destroy]

        def new
          @ticket_update_form = TicketUpdateForm.new(@ticket)
        end

        def edit
        end

        def create
          @ticket_update_form = TicketUpdateForm.new(@ticket, ticket_update_create_params)

          if @ticket_update_form.save
            redirect_to admin_item_ticket_url(@item, @ticket), success: "Ticket update was successfully created.", status: :see_other
          else
            render :new, status: :unprocessable_content
          end
        end

        def update
          if @ticket_update.update(ticket_update_update_params)
            redirect_to admin_item_ticket_url(@item, @ticket), success: "Ticket update was successfully saved.", status: :see_other
          else
            render :edit, status: :unprocessable_content
          end
        end

        def destroy
          @ticket_update.destroy
          redirect_to admin_item_ticket_url(@item, @ticket), success: "Ticket update was successfully destroyed.", status: :see_other
        end

        private

        def set_ticket
          @ticket = @item.tickets.find(params[:ticket_id])
        end

        def set_ticket_update
          @ticket_update = @ticket.ticket_updates.find(params[:id])
        end

        def ticket_update_create_params
          params.require(:ticket_update_form).permit(:title, :time_spent, :body, :status, :retired_reason).merge(creator: current_user)
        end

        def ticket_update_update_params
          params.require(:ticket_update).permit(:title, :time_spent, :body)
        end
      end
    end
  end
end

app/controllers/admin/items/tickets_controller.rb
module Admin
  module Items
    class TicketsController < BaseController
      before_action :set_ticket, only: %i[show edit update destroy]

      def index
        @tickets = @item.tickets.all.order(:status, updated_at: :desc)
      end

      def show
        @ticket_updates = @ticket.ticket_updates.includes(:audit)

        @events = @ticket_updates.to_a.concat(@ticket.audits).sort_by(&:created_at)
      end

      def new
        @ticket = Ticket.new
      end

      def edit
      end

      def create
        @ticket = @item.tickets.new(ticket_params.except(:retired_reason))

        if @ticket.save
          update_item_status!(@ticket)
          redirect_to admin_item_ticket_url(@item, @ticket), success: "Ticket was successfully created.", status: :see_other
        else
          render :new, status: :unprocessable_content
        end
      end

      def update
        if @ticket.update(ticket_params.except(:retired_reason))
          update_item_status!(@ticket)
          redirect_to admin_item_ticket_url(@item, @ticket), success: "Ticket was successfully updated.", status: :see_other
        else
          render :edit, status: :unprocessable_content
        end
      end

      def destroy
        @ticket.destroy
        redirect_to admin_item_tickets_url(@item), success: "Ticket was successfully destroyed.", status: :see_other
      end

      private

      def update_item_status!(ticket)
        status = ticket.retired? ? Item.statuses["retired"] : Item.statuses["maintenance"]
        retired_reason = ticket.retired? ? ticket_params[:retired_reason] || Item.retired_reasons["broken"] : nil
        @ticket.item.update!(status:, retired_reason:)
      end

      def set_ticket
        @ticket = Ticket.find(params[:id])
      end

      def ticket_params
        params.require(:ticket).permit(:title, :body, :status, :retired_reason, tag_list: []).merge(creator_id: current_user.id)
      end
    end
  end
end

app/helpers/ticket_updates_helper.rb
# frozen_string_literal: true

module TicketUpdatesHelper
end

app/helpers/tickets_helper.rb
# frozen_string_literal: true

module TicketsHelper
  def ticket_status_options
    Ticket.statuses.map do |key, value|
      description = " (#{Ticket::STATUS_DESCRIPTIONS[key]})" if Ticket::STATUS_DESCRIPTIONS[key]
      ["#{Ticket::STATUS_NAMES[key]}#{description}", key]
    end
  end

  def audit_ticket_status(audit)
    status_change = audit.audited_changes["status"]
    case status_change
    when Array
      ticket_status_name(status_change[1])
    when String
      ticket_status_name(status_change)
    end
  end

  def ticket_status_name(status)
    Ticket::STATUS_NAMES[status]
  end
end

app/views/admin/items/tickets/ticket_updates/edit.html.erb
<%= render "admin/items/profile" do %>
  <h1 class="h3 mt-2">Edit Ticket Update</h1>

  <%= form_with(model: @ticket_update, url: admin_item_ticket_ticket_update_path(@item, @ticket, @ticket_update), builder: SpectreFormBuilder) do |form| %>
    <%= form.errors %>
    <%= form.rich_text_area :body %>
    <%= form.number_field :time_spent, hint: "How many minutes did you spend on this?" %>

    <%= tag.div class: "form-group" do %>
      <%= form.label "Change Ticket Status" %>
      <p class="form-input-hint">You can change the ticket status on the <%= link_to "ticket edit page", edit_admin_item_ticket_path(@item, @ticket) %> or by creating a new Ticket Update.</p>
    <% end %>

    <%= form.actions do %>
      <%= form.submit "Save" %>
    <% end %>
  <% end %>

  <p class="mt-5"><%= button_to "Destroy this ticket update", [:admin, @item, @ticket, @ticket_update], method: :delete, data: {turbo_confirm: "Are you sure?"} %></p>
<% end %>

app/views/admin/items/tickets/ticket_updates/index.html.erb
<%= render "admin/items/profile" do %>
  <%= link_to "New Maintenance Report", new_admin_item_maintenance_report_path(@item), class: "btn" %>

  <div class="timeline item-edit-history maintenance-report-index mt-5">
    <% @events.each do |event| %>
      <% next if ItemAudit === event && !event.audited_changes["status"] %>
      <% next if @events.any? { |e| TicketUpdate === e && e.audit == event } %>

      <div class="timeline-item <%= "timeline-skip" if disconnected_maintenance_report_event?(event) %>" id="<%= dom_id(event) %>">

        <div class="timeline-left">
          <a class="timeline-icon" href="#<%= dom_id(event) %>"></a>
        </div>
        <div class="timeline-content">
          <% if TicketUpdate === event %>
            <% maintenance_report = event %>
            <div class="tile-content">
              <h3 class="h5 mb-0"><%= maintenance_report.title %></h3>
              <p class="mb-2"><%= display_date maintenance_report.created_at, :short_date %>
                <% if maintenance_report.creator.present? %>
                  &mdash; <%= link_to_member(maintenance_report.creator.member) %>
                <% end %>
                <% if maintenance_report.time_spent.present? %>(<%= maintenance_report.time_spent %> minutes)<% end %>
              </p>
              <div class="trix_content mb-2">
                <%= maintenance_report.body %>
              </div>
              <% if maintenance_report.audit %>
                <h3 class="h6 mb-0">status changed to <span class="text-bold"><%= audit_item_status maintenance_report.audit %></span></h3>
              <% end %>
              <span class="mt-2 text-small">
                <%= link_to "Edit", edit_admin_item_maintenance_report_path(@item, maintenance_report) %>
              </span>
            </div>
          <% else %>
            <% audit = event %>
            <div class="tile-content">
              <h3 class="h6 mb-0">status changed to <span class="text-bold"><%= audit_item_status audit %></span></h3>
              <p class="text-small">
                <%= display_date event.created_at, :short_date %>
                <% if audit.user.present? %>
                  &mdash; <%= link_to_member(audit.user.member) %>
                <% end %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

app/views/admin/items/tickets/ticket_updates/new.html.erb
<%= render "admin/items/profile" do %>
    <h1 class="h3 mt-2">New Ticket Update</h1>

    <%= form_with(model: @ticket_update_form, url: admin_item_ticket_ticket_updates_path(@item, @ticket, @ticket_update), builder: SpectreFormBuilder) do |form| %>
        <%= form.errors %>
        <%= form.rich_text_area :body %>
        <%= form.number_field :time_spent, hint: "How many minutes did you spend on this?" %>

        <div data-controller="conditional-field" data-conditional-field-trigger-value="<%= Ticket.statuses["retired"] %>">
            <%= form.select :status, options_for_select(ticket_status_options, @ticket_update_form.status), {label: "Change Ticket Status"}, data: {action: "conditional-field#change", "conditional-field-target": "parent"} %>
            <%= tag.div data: {"conditional-field-target": "child"}, class: "conditional-field-child" do %>
                <%= form.select :retired_reason, options_for_select(item_retired_reason_options), label: "Reason to retire" %>
            <% end %>
        </div>

        <%= form.actions do %>
            <%= form.submit "Save" %>
        <% end %>
    <% end %>
<% end %>

app/views/admin/items/tickets/ticket_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time spent:</strong>
  <%= @maintenance_report.time_spent %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @maintenance_report.creator_id %>
</p>

<%= link_to "Edit", edit_maintenance_report_path(@maintenance_report) %> |
<%= link_to "Back", maintenance_reports_path %>