config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations"}

  namespace :signup do
    resources :members, only: [:new, :create]
    scope :documents do
      get :agreement, to: "documents#agreement"
      get :rules, to: "documents#rules"

      resource :acceptance, only: [:create, :destroy]
    end
    resources :payments, only: [:new, :create] do
      get :callback, on: :collection
      post :skip, on: :collection
    end
    resources :redemptions, only: [:new, :create]

    get "confirmation", to: "confirmations#show"
    get "/", to: "home#index"
  end

  namespace :account do
    resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :borrow_policy_approvals, only: [:create]
    resources :holds, only: [:index, :create, :destroy] do
      get :history, to: "holds#history", on: :collection
    end
    resources :loans, only: :index do
      get :history, to: "loans#history", on: :collection
      post :renew_all, to: "loans#renew_all", on: :collection
    end
    resource :member, only: [:show, :edit, :update]
    get :agreement, to: "members#agreement"
    get :code_of_conduct, to: "members#code_of_conduct"
    get :borrow_policy, to: "members#borrow_policy"
    resource :password, only: [:edit, :update]
    resources :renewals, only: :create
    resources :renewal_requests, only: :create
    resources :for_later_list_items, path: :for_later, only: [:index, :create, :destroy]
    get "/", to: "home#index", as: "home"

    if FeatureFlags.reservable_items_enabled?
      resources :reservation_holds, only: [:create, :update, :destroy]
      resource :current_reservation, only: [:create, :destroy]
      resources :reservations do
        get :past, to: "reservations#past", on: :collection
        scope module: "reservations" do
          resources :reservation_holds
          resource :submission
        end
      end
      resources :item_pools
    end
  end

  namespace :renewal do
    resource :member, only: [:edit, :update]
    scope :documents do
      get :agreement, to: "documents#agreement"
      get :rules, to: "documents#rules"

      resource :acceptance, only: [:create, :destroy]
    end
    resources :payments, only: [:new, :create] do
      get :callback, on: :collection
      post :skip, on: :collection
    end
    resources :redemptions, only: [:new, :create]

    get "confirmation", to: "confirmations#show"
    get "/", to: "home#index"
  end

  namespace :volunteer do
    resources :shifts, only: [:index, :create, :destroy]
    resources :attendees, only: [:create, :destroy]
    get "event", to: "shifts#event"
    resource :session, only: [:destroy]
  end
  get "/auth/google_oauth2/callback", to: "volunteer/sessions#create"
  get "/auth/failure", to: "volunteer/sessions#failure"

  namespace :admin do
    resources :documents, only: [:show, :edit, :update, :index]
    resources :borrow_policies, only: [:index, :edit, :update, :show] do
      resources :borrow_policy_approvals, only: [:index, :edit, :update, :create], path: :approvals
    end
    resources :categories, except: :show
    resources :gift_memberships
    resources :questions, except: [:destroy] do
      patch :archive, on: :member
      patch :unarchive, on: :member
    end
    resources :appointments, only: [:index, :show, :edit, :update, :destroy] do
      resources :holds, only: [:create, :destroy], controller: :appointment_holds
      resources :loans, only: [:create, :destroy], controller: :appointment_loans
      resources :checkouts, only: [:create], controller: :appointment_checkouts
      resources :checkins, only: [:create], controller: :appointment_checkins
      resource :completion, only: [:create, :destroy], controller: :appointment_completions
      resource :pull, only: [:create, :destroy], controller: :appointment_pulls
      resource :detail_completion, only: [:create, :destroy], controller: :appointment_detail_completions
      resource :detail_pull, only: [:create, :destroy], controller: :appointment_detail_pulls
    end
    resources :manage_features, only: [:index, :update]
    resources :items do
      scope module: "items" do
        resources :attachments
        resource :loan_history, only: :show
        resource :history, only: :show
        resources :holds, only: :index do
          patch :remove, action: "remove"
          scope module: "holds" do
            resource :position, only: :update
          end
        end
        resources :notes
        if ENV["FEATURE_MAINTENANCE_WORKFLOW"] == "on"
          resources :tickets do
            scope module: "tickets" do
              resources :ticket_updates, only: [:new, :create, :edit, :update, :destroy]
            end
          end
        end
      end

      get :number
      resource :image, only: [:edit, :update]
      # resource :manual_import, only: [:edit, :update]
    end
    resources :loan_summaries, only: :index
    resources :loans, only: [:index, :create, :update, :destroy]
    resources :renewals, only: [:create, :destroy]
    resources :bulk_renewals, only: [:update]

    resources :members do
      scope module: "members" do
        resources :holds, only: [:create, :index, :destroy] do
          post :lend, on: :member
          get :history, on: :collection
        end
        resource :hold_loan, only: :create
        resource :lookup, only: :show
        resources :memberships, only: [:index, :new, :create, :update]
        resources :payments, only: [:new, :create]
        resource :verification, only: [:edit, :update]
        resources :appointments, only: [:index, :create]
        resources :notifications, only: :index
        resources :loan_summaries, only: :index
        resources :notes
        resource :password, only: [:edit, :update]
      end

      member do
        post :resend_verification_email
      end
    end

    namespace :reports do
      resources :memberships, only: :index
      resources :items_in_maintenance, only: :index
      resources :missing_items, only: :index
      resources :monthly_activities, only: :index
      resources :member_requests, only: :index
      resources :notifications, only: :index
      resources :potential_volunteers, only: :index
      resources :shifts, only: :index
      resources :items_without_image, only: :index
      resources :items_with_holds, only: :index
      resources :zipcodes, only: :index
      get "money", to: "money#index"
      get "members-with-overdue-loans", to: "members_with_overdue_loans#index"
    end

    namespace :settings do
      get "closing", to: "closing#index"
      post "closing/extend_holds", to: "closing#extend_holds"
      resource :email_settings do
        get :preview, on: :member
      end
      resources :library_updates
      resources :exports, only: [:index] do
        post :items, on: :collection
        post :members, on: :collection
      end
    end

    resources :holds, only: [:index]
    resources :users
    resources :renewal_requests, only: [:index, :update]

    get "search", to: "searches#show"

    get "/ui/names", to: "ui#names"
    get "/ui/brands", to: "ui#brands"
    get "/ui/sizes", to: "ui#sizes"
    get "/ui/strengths", to: "ui#strengths"
    get "/ui/available_items", to: "ui#available_items"
    get "/ui/members", to: "ui#members"

    if FeatureFlags.reservable_items_enabled?
      resources :reservation_policies
      resources :item_pools do
        scope module: "item_pools" do
          resource :availability, only: :show
          resources :reservable_items
        end
      end
      resources :reservations do
        scope module: "reservations" do
          resources :items, as: "loans", controller: "reservation_loans", only: [:index, :create, :destroy]
          resources :check_ins, only: [:create, :destroy]
          resources :reservation_holds
          resources :pending_reservation_items, only: [:update, :destroy]
          resource :status, only: :update
          resource :review, only: [:edit, :update, :show]
          resource :item_pool_search, only: :show
          resource :questions, only: :show
        end
      end
    end

    get "/", to: "dashboard#index", as: "dashboard"
  end

  if Rails.env.development?
    post "/dev/time", to: "dev#set_time"
    delete "/dev/time", to: "dev#clear_time"
  end

  get "/dev/styles", to: "dev#styles"

  namespace :super_admin do
    resources :libraries
  end

  resources :items, only: [:index, :show]
  if FeatureFlags.reservable_items_enabled?
    resources :item_pools, only: [:index, :show], path: "camping_items"
    resources :reservation_holds, only: :create
  end
  resources :documents, only: :show

  post "/twilio/callback", to: "twilio#callback"

  # Mount dashboards for admins
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    mount Blazer::Engine => "blazer"
  end

  root to: "home#index"

  if Rails.env.test?
    get "/test/google_auth", to: "test#google_auth"
  end

  %w[404 406 422 500 503].each do |code|
    match code, to: "errors#show", via: :all, code: code, as: "error_#{code}"
  end
end

app/models/reservable_item.rb
# A ReservableItem is an item that can be checked out while fulfilling a Reservation via a ReservationLoan.
class ReservableItem < ApplicationRecord
  include ItemStatuses
  include ItemNumbering

  belongs_to :creator, class_name: "User"
  belongs_to :item_pool, counter_cache: true
  has_many :reservation_loans
  has_one_attached :image

  store_accessor :myturn_metadata,
    :image_url, :dimensions, :weight, :item_type, :supplier

  enum :power_source, {
    solar: "solar",
    gas: "gas",
    air: "air",
    electric_corded: "electric (corded)",
    electric_battery: "electric (battery)"
  }

  validates :power_source, inclusion: {in: power_sources.keys}, allow_blank: true

  acts_as_tenant :library

  monetize :purchase_price_cents,
    allow_nil: true,
    disable_validation: true

  def import_myturn_image
    return if myturn_metadata["image_url"].blank?

    url = URI.parse(myturn_metadata["image_url"])
    filename = File.basename(url.path)
    downloaded_image = url.open
    image.attach(io: downloaded_image, filename:)
  end
end

app/controllers/admin/item_pools/availabilities_controller.rb
module Admin
  module ItemPools
    class AvailabilitiesController < BaseController
      def show
        reserved_by_date = @item_pool.reserved_by_date(Time.current.beginning_of_month, Time.current.end_of_month)
        @month_calendar = GroupLending::MonthCalendar.new(reserved_by_date)
      end
    end
  end
end

app/controllers/admin/item_pools/base_controller.rb
module Admin
  module ItemPools
    class BaseController < Admin::BaseController
      before_action :load_item_pool

      private

      def load_item_pool
        @item_pool = ItemPool.find(params[:item_pool_id])
      end
    end
  end
end

app/controllers/admin/item_pools/reservable_items_controller.rb
module Admin
  module ItemPools
    class ReservableItemsController < BaseController
      before_action :set_reservable_item, only: %i[show edit update destroy]

      def index
      end

      def show
      end

      def new
        @reservable_item = @item_pool.reservable_items.new
      end

      def edit
      end

      def create
        @reservable_item = @item_pool.reservable_items.new(reservable_item_params.merge(creator: current_user))

        if @reservable_item.save
          redirect_to admin_item_pool_reservable_items_url(@item_pool), success: "Reservable item was successfully created."
        else
          render :new, status: :unprocessable_content
        end
      end

      def update
        if @reservable_item.update(reservable_item_params)
          redirect_to admin_item_pool_reservable_items_url(@item_pool), success: "Reservable item was successfully updated."

        else
          render :edit, status: :unprocessable_content
        end
      end

      def destroy
        @reservable_item.destroy!

        redirect_to admin_item_pool_reservable_items_url(@item_pool), success: "Reservable item was successfully destroyed."
      end

      private

      def set_reservable_item
        @reservable_item = @item_pool.reservable_items.find(params[:id])
      end

      def reservable_item_params
        params.require(:reservable_item).permit(
          :name, :status, :size, :brand, :model, :strength, :power_source, :location_area, :location_shelf, :url,
          :purchase_price, :purchase_link
        )
      end
    end
  end
end

app/controllers/admin/item_pools_controller.rb
module Admin
  class ItemPoolsController < BaseController
    include Pagy::Backend

    before_action :set_item_pool, only: %i[show edit update destroy]

    def index
      item_pool_scope = ItemPool.all

      if params[:category]
        @category = CategoryNode.where(id: params[:category]).first
        redirect_to(items_path, error: "Category not found") && return unless @category

        item_pool_scope = @category.item_pools
      end

      item_pool_scope = item_pool_scope.includes(:categories).order("name ASC")

      @pagy, @item_pools = pagy(item_pool_scope)
      @categories = CategoryNode.with_item_pools
    end

    def show
    end

    def new
      @item_pool = ItemPool.new
      set_categories
      set_reservation_policy_options
    end

    def edit
      set_categories
      set_reservation_policy_options
    end

    def create
      @item_pool = ItemPool.new(item_pool_params.merge(creator: current_user))

      if @item_pool.save
        redirect_to admin_item_pool_url(@item_pool), success: "Item pool was successfully created."
      else
        set_categories
        set_reservation_policy_options
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @item_pool.update(item_pool_params)
        redirect_to admin_item_pool_url(@item_pool), success: "Item pool was successfully updated."
      else
        set_categories
        set_reservation_policy_options
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @item_pool.destroy!

      redirect_to admin_item_pools_url, success: "Item pool was successfully destroyed."
    end

    private

    def set_item_pool
      @item_pool = ItemPool.find(params[:id])
    end

    def item_pool_params
      params.require(:item_pool).permit(
        :name, :other_names, :description, :uniquely_numbered, :unnumbered_count,
        :reservation_policy_id, :checkout_notice, :max_reservable_percentage_points, category_ids: []
      )
    end

    def set_categories
      @categories = CategoryNode.all
    end

    def set_reservation_policy_options
      @reservation_policy_options = ReservationPolicy.all.order(:name).map do |reservation_policy|
        [reservation_policy.name, reservation_policy.id]
      end
    end
  end
end

app/controllers/item_pools_controller.rb
class ItemPoolsController < ApplicationController
  include Pagy::Backend

  before_action :set_item_pool, only: :show

  def index
    item_pool_scope = ItemPool.all

    if params[:category]
      @category = CategoryNode.where(id: params[:category]).first
      redirect_to(items_path, error: "Category not found") && return unless @category

      item_pool_scope = @category.item_pools
    end

    item_pool_scope = item_pool_scope.includes(:categories).order("name ASC")

    @pagy, @item_pools = pagy(item_pool_scope)
    @categories = CategoryNode.with_item_pools
  end

  def show
    if current_reservation
      @reservation_hold = current_reservation.hold_for_item_pool(@item_pool) || current_reservation.reservation_holds.new(item_pool: @item_pool)
    end
    @upcoming_reservations = current_member.reservations.upcoming if current_member
  end

  private

  def set_item_pool
    @item_pool = ItemPool.find(params[:id])
  end
end

app/views/admin/item_pools/reservable_items/_form.html.erb
<%= form_with(model: reservable_item, url: [:admin, reservable_item.item_pool, reservable_item], builder: SpectreFormBuilder) do |form| %>
  <div class="columns">
    <div class="column col-4 col-sm-12">
      <%= form.autocomplete_text_field :size, path: admin_ui_sizes_path(format: :json),
            hint: "Blade or bit diameter, width or height; e.g. 3/8\"" %>
    </div>
    <div class="column col-4 col-sm-12">
      <%= form.autocomplete_text_field :strength, path: admin_ui_strengths_path(format: :json),
            hint: "i.e. voltage or amps; e.g. 18v, heavy duty" %>
    </div>
    <div class="column col-4 col-sm-12">
      <%= form.select :power_source, options_for_select(item_power_source_options, reservable_item.power_source), include_blank: "Not powered", hint: "Specify how the item is powered, if it is powered" %>
    </div>
  </div>

  <div class="columns">
    <div class="column col-4 col-sm-12">
      <%= form.autocomplete_text_field :brand, path: admin_ui_brands_path(format: :json), hint: "e.g. Dewalt, Craftsman, Singer" %>
    </div>
    <div class="column col-4 col-sm-12">
      <%= form.text_field :model, hint: "e.g. ABC-123; usually found on the back or bottom" %>
    </div>
    <div class="column col-4 col-sm-12">
      <%= form.text_field :serial, hint: "Usually near the model number" %>
    </div>
  </div>

  <%= form.select :status, options_for_select(item_status_options, reservable_item.status || ReservableItem.statuses[:active]), prompt: true, hint: "Only active items can be checked out" %>

  <fieldset>
    <legend>Item Location</legend>
    <div class="columns">
      <div class="column col-4 col-sm-12">
        <%= form.text_field :location_area, label: "Area", hint: "General location of the item" %>
      </div>
      <div class="column col-4 col-sm-12">
        <%= form.text_field :location_shelf, label: "Shelf", hint: "Location within the area" %>
      </div>
    </div>
  </fieldset>

  <%= form.text_field :url, label: "URL", hint: "Link to more info, e.g. a manufacturer website" %>

  <div class="columns mt-2">
    <div class="column col-4 col-sm-12">
      <%= form.money_field :purchase_price, label: "Purchase price", hint: "What would it cost to replace?" %>
    </div>
    <div class="column col-8 col-sm-12">
      <%= form.text_field :purchase_link %>
    </div>
  </div>

  <fieldset>
    <legend>Item Image</legend>
    <div class="columns">
      <div class="column col-4 col-sm-12">
        <%= form.file_field :image, hint: "Take a photo with the device's camera", data: {"turbo-permanent": true} %>
      </div>
      <div class="column col-4 col-sm-12">
        <%= form.check_box :delete_image, label: "Delete current image", required: false %>
      </div>
    </div>
  </fieldset>

  <% unless reservable_item.new_record? %>
    <details>
      <summary>Number: <strong><%= reservable_item.number %></strong></summary>
      <%= form.text_field :number, hint: "Only change this with good reason! Next available number is #{ReservableItem.next_number}." %>
    </details>
  <% end %>

  <%= form.actions do %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/admin/item_pools/reservable_items/_reservable_item.html.erb
<div id="<%= dom_id reservable_item %>">
  <p>
    <%= link_to reservable_item.name, admin_reservable_item_path(reservable_item) %>
    belongs to the item pool
    <%= link_to reservable_item.item_pool.name, admin_item_pool_path(reservable_item.item_pool) %>
  </p>
</div>

app/views/admin/item_pools/reservable_items/index.html.erb
<%= render "admin/item_pools/profile" do %>
  <div class="item-pool-show">
    <table class="table">
      <thead>
        <th>#</th>
        <th>Status</th>
        <th>Brand/Model</th>
        <th>Size/Strength</th>
        <th>Serial</th>
        <th>Power Source</th>
        <th>Location</th>
      </thead>
      <tbody>
        <% @item_pool.reservable_items.each do |reservable_item| %>
          <tr>
            <td><%= link_to reservable_item.number, edit_admin_item_pool_reservable_item_path(@item_pool, reservable_item) %></td>
            <td><%= ReservableItem::STATUS_NAMES[reservable_item.status] %></td>
            <td><%= reservable_item.brand || "-" -%> / <%= reservable_item.model || "-" -%></td>
            <td><%= reservable_item.size || "-" -%> / <%= reservable_item.strength || "-" -%></td>
            <td><%= reservable_item.serial || "-" -%></td>
            <td><%= reservable_item.power_source || "-" -%></td>
            <td><%= reservable_item.location_area || "-" -%>, <%= reservable_item.location_shelf || "-" -%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>